nurcinema-master/root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    
    path('', include('movies.urls'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nurcinema-master/movies/models.py
from django.db.models import Model, CharField, IntegerField, \
    ForeignKey, TextField, DateField, FloatField, BooleanField,\
    DateTimeField, TextChoices, ImageField, FileField, CASCADE,\
    SlugField, ManyToManyField
from django.template.defaultfilters import slugify
from django.db.utils import IntegrityError

class QualityChoices(TextChoices):
    HD = 'hd', 'HD'
    FULL_HD = 'full_hd', 'Full HD'
    _4K = '_4k', '4K'


class MovieStatusChoices(TextChoices):
    RELEASED = 'released', 'Released'
    COMING_SOON = 'coming_soon', 'Coming Soon'
    IN_PRODUCTION = 'in_production', 'In Production'
    POST_PRODUCTION = 'post_production', 'Post Production'
    CANCELLED = 'cancelled', 'Cancelled'
    ANNOUNCED = 'announced', 'Announced'
    AIRING = 'airing', 'Airing'


class MovieTypeChoices(TextChoices):
    REGULAR = 'regular', 'Regular'
    BANNER = 'banner', 'Banner'


class Movie(Model):
    title = CharField(max_length=555, help_text="Kino sarlavhasi")
    description = TextField(help_text="Kino tavsilotlari")
    duration = IntegerField(help_text="Kino davomiyligi (minutda)")
    movie_type = CharField(max_length=255, help_text="Kino janri")
    studios = CharField(max_length=350, help_text="Ishlab chiqaruvchi studio")
    release_date = DateField(help_text="Kino premyerasi sana")
    rating = FloatField(help_text="Kino reytingi")
    views = IntegerField(help_text="Ko'rishlar soni")
    is_active = BooleanField(default=True, help_text="Aktivligi")

    quality = CharField(max_length=20, choices=QualityChoices.choices)
    scores = FloatField(help_text="Scoring")
    
    status = CharField(max_length=25, choices=MovieStatusChoices.choices,
                       default=MovieStatusChoices.COMING_SOON,
                       help_text="Kino statusi")

    image = ImageField(upload_to='movie_images/', help_text="Kino banneri")
    video = FileField(upload_to='movies/', help_text="Kino/Treyler fayli")
    thumb = FileField(upload_to='movie_thumbs/', help_text="Thumb fayli",
                      null=True, blank=True)

    type = CharField(max_length=20, choices=MovieTypeChoices.choices,
                     default=MovieTypeChoices.REGULAR, 
                     help_text="Kino joylashuvi")
    
    slug = SlugField(unique=True, null=True, blank=True)
    created_at = DateTimeField(auto_now=True)
    updated_at = DateTimeField(auto_now_add=True)
    movie_genre = ManyToManyField('Genre', through='MovieGenre')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            try:
                self.slug = slugify(self.title)
            except IntegrityError:
                self.slug += str(1)                
            print(f"{self.slug=}")
        super().save(*args, **kwargs)


class Genre(Model):
    name = CharField(max_length=255, help_text="Kino Janri")

    def __str__(self):
        return self.name
  

class MovieGenre(Model):
    movie = ForeignKey(Movie, on_delete=CASCADE)
    genre = ForeignKey(Genre, on_delete=CASCADE)

nurcinema-master/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NURCINEMA</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <!-- <div id="preloder">
        <div class="loader"></div>
    </div> -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}">
                            <img src="{% static 'img/logo2.png' %}" alt="Logo">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="{% url 'home' %}">Homepage</a></li>
                                <li><a href="#">Categories <span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        
                                        <li><a href="{% url 'movie_detail' movie_detail_slug %}">Movie Details</a></li>
                                        <li><a href="{% url 'watch' movie_detail_slug %}">Movie Watching</a></li>
                                       {% if request.user.is_authenticated %}
                                       <li><a href="{% url 'logout' %}">Logout</a></li>
                                       {% else %}
                                        <li><a href="{% url 'register' %}">Sign Up</a></li>
                                        <li><a href="{% url 'login' %}">Login</a></li>
                                        {% endif %}
                                    </ul>
                                </li>
                              
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'logout' %}"><span class="fa fa-sign-out"></span></a>
                        {% else %}
                        <a href="{% url 'login' %}"><span class="icon_profile"></span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    {% block legenda %}

    {% endblock %}

    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="{% url 'home' %}"><img src="{% static 'img/logo2.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="{% url 'home' %}">Homepage</a></li>
                            <li><a href="#">Categories</a></li>
                        
                        </ul>
                    </div>
                </div>
          
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form" method="get" action="">
                <input type="text" id="search-input" placeholder="Search here....." name="q">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>

</html>

nurcinema-master/templates/blog-details.html
{% extends 'base.html' %}
{% block legenda %}
    <!-- Header End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="blog__details__title">
                        <h6>Action, Magic <span>- March 08, 2020</span></h6>
                        <h2>Anime for Beginners: 20 Pieces of Essential Viewing</h2>
                        <div class="blog__details__social">
                            <a href="#" class="facebook"><i class="fa fa-facebook-square"></i> Facebook</a>
                            <a href="#" class="pinterest"><i class="fa fa-pinterest"></i> Pinterest</a>
                            <a href="#" class="linkedin"><i class="fa fa-linkedin-square"></i> Linkedin</a>
                            <a href="#" class="twitter"><i class="fa fa-twitter-square"></i> Twitter</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="img/blog/details/blog-details-pic.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__text">
                            <p>As a result the last couple of eps haven’t been super exciting for me, because they’ve
                                been more like settling into a familiar and comfortable routine.  We’re seeing character
                                growth here but it’s subtle (apart from Shouyou, arguably).  I mean, Tobio being an
                                asshole is nothing new – it’s kind of the foundation of his entire character arc. 
                                Confronting whether his being an asshole is a problem for the Crows this directly is a
                                bit of an evolution, and probably an overdue one at that, but the overall dynamic with
                            Kageyama is basically unchanged.</p>
                        </div>
                        <div class="blog__details__item__text">
                            <h4>Tobio-Nishinoya showdown:</h4>
                            <img src="img/blog/details/bd-item-1.jpg" alt="">
                            <p>In Japan the idea of a first-year speaking to a senior the way Kageyama did to Asahi is a
                                lot more shocking than it would be in the West, but Tobio calling out teammates in
                                genuinely rude fashion in the middle of a match is what got him isolated in the first
                                place.  It’s better for the Crows to sort this out in practice matches than the real
                                deal, but this is really on Tobio – he has to figure out how to co-exist with others in
                            a team environment.</p>
                        </div>
                        <div class="blog__details__item__text">
                            <h4>Nanatsu no Taizai: Kamigami No Gekirin</h4>
                            <img src="img/blog/details/bd-item-2.jpg" alt="">
                            <p>In Japan the idea of a first-year speaking to a senior the way Kageyama did to Asahi is a
                                lot more shocking than it would be in the West, but Tobio calling out teammates in
                                genuinely rude fashion in the middle of a match is what got him isolated in the first
                                place.  It’s better for the Crows to sort this out in practice matches than the real
                                deal, but this is really on Tobio – he has to figure out how to co-exist with others in
                            a team environment.</p>
                        </div>
                        <div class="blog__details__item__text">
                            <h4>ID:Ianvaded:</h4>
                            <img src="img/blog/details/bd-item-3.jpg" alt="">
                            <p>In Japan the idea of a first-year speaking to a senior the way Kageyama did to Asahi is a
                                lot more shocking than it would be in the West, but Tobio calling out teammates in
                                genuinely rude fashion in the middle of a match is what got him isolated in the first
                                place.  It’s better for the Crows to sort this out in practice matches than the real
                                deal, but this is really on Tobio – he has to figure out how to co-exist with others in
                            a team environment.</p>
                        </div>
                        <div class="blog__details__tags">
                            <a href="#">Healthfood</a>
                            <a href="#">Sport</a>
                            <a href="#">Game</a>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="blog__details__btns__item">
                                        <h5><a href="#"><span class="arrow_left"></span> Building a Better LiA...</a>
                                        </h5>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="blog__details__btns__item next__btn">
                                        <h5><a href="#">Mugen no Juunin: Immortal – 21 <span
                                            class="arrow_right"></span></a></h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="blog__details__comment">
                                <h4>3 Comments</h4>
                                <div class="blog__details__comment__item">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-1.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>John Smith</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                                <div class="blog__details__comment__item blog__details__comment__item--reply">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-2.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>Elizabeth Perry</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                                <div class="blog__details__comment__item">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-3.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>Adrian Coleman</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                            </div>
                            <div class="blog__details__form">
                                <h4>Leave A Commnet</h4>
                                <form action="#">
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-6">
                                            <input type="text" placeholder="Name">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6">
                                            <input type="text" placeholder="Email">
                                        </div>
                                        <div class="col-lg-12">
                                            <textarea placeholder="Message"></textarea>
                                            <button type="submit" class="site-btn">Send Message</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Details Section End -->

{% endblock %}

nurcinema-master/templates/login.html
{% extends 'base.html' %}
{% block legenda %}
    <!-- Header End -->

    <!-- Normal Breadcrumb Begin -->
  
    <!-- Normal Breadcrumb End -->

    <!-- Login Section Begin -->
    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Login</h3>


                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" placeholder="Username" name="username">
                                <span class="icon_mail"></span>
                            </div>
                            <div class="input__item">
                                <input type="text" placeholder="Password" name="password">
                                <span class="icon_lock"></span>
                            </div>
                            <button type="submit" class="site-btn">Login Now</button>
                        </form>


                        <!-- <a href="#" class="forget_pass">Forgot Your Password?</a> -->
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__register">
                        <h3>Dont’t Have An Account?</h3>
                        <a href="{% url 'register' %}" class="primary-btn">Register Now</a>
                    </div>
                </div>
            </div>
            <div class="login__social">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6">
                        <div class="login__social__links">
                            <span>or</span>
                            <ul>
                                <li><a href="#" class="facebook"><i class="fa fa-facebook"></i> Sign in With
                                Facebook</a></li>
                                <li><a href="#" class="google"><i class="fa fa-google"></i> Sign in With Google</a></li>
                                
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->

    <!-- Footer Section Begin -->
{% endblock %}

nurcinema-master/templates/movie-details.html
{% extends 'base.html' %}
 
  
{% block legenda %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <a href="./categories.html">Categories</a>
                        <span>Romance</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg" data-setbg="{{ movie.image.url }}">
                            <div class="comment"><i class="fa fa-comments"></i> 11</div>
                            <div class="view"><i class="fa fa-eye"></i>{{ movie.views }}</div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="anime__details__text">
                            <div class="anime__details__title">
                                <h3>{{ movie.title }}</h3>
                            </div>
                            <div class="anime__details__rating">
                                <div class="rating">
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star-half-o"></i></a>
                                </div>
                                <span>1.029 Votes</span>
                            </div>
                            <p>{{ movie.descrption }}</p>
                            <div class="anime__details__widget">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Type:</span>{{ movie.movie_type }}</li>
                                            <li><span>Studios:</span>{{ movie.studios }}</li>
                                            <li><span>Date aired:</span>{{ movie.release_date }}</li>
                                            <li><span>Status:</span>{{ movie.status }}</li>
                                            <li><span>Genre:</span>
                                                {% for genre in movie.moviegenre_set.all %}

                                                    {% if forloop.last %}
                                                        {{ genre.genre.name }}
                                                    {% else %}
                                                        {{ genre.genre.name }}
                                                    {% endif %}


                                                    {% endfor %}
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <ul>
                                                <li><span>Scores:</span>{{ movie.scores }} / 1,515</li>
                                                <li><span>Rating:</span>{{ movie.rating }}</li>
                                                <li><span>Duration:</span>{{ movie.duration }}</li>
                                                <li><span>Quality:</span>{{ movie.quality }}</li>
                                                <li><span>Views:</span>{{ movie.views }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="anime__details__btn">
                                    <a href="#" class="follow-btn"><i class="fa fa-heart-o"></i> Follow</a>
                                    <a href="{% url 'watch' movie.slug %}" class="watch-btn"><span>Watch Now</span> <i
                                        class="fa fa-angle-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="anime__details__review">

                                {% if reviews %}
                                    <div class="section-title">
                                    <h5>Reviews</h5>
                                    </div>
    
                                    {% for review in reviews %}
                                    <div class="anime__review__item">
                                    <div class="anime__review__item__pic">
                                        <img src="{{ review.movie.image.url }}" alt="">
                                    </div>
                                    <div class="anime__review__item__text">
                                        <h6>{{ review.user.username }}<span>{{ review.time_posted }}</span></h6>
                                        <p>{{ review.comment }}</p>
                                    </div>
                                </div>
                                    {% endfor %}
                                
                                {% else %}

                                <div class="section-title">
                                    <h5>No Reviews Yet</h5>
                                    </div>
                                {% endif %}


                            


                                </div>
                            {% if request.user.is_authenticated %}
                            <div class="anime__details__form">
                                <div class="section-title">
                                    <h5>Your Comment</h5>
                                </div>
                                <form action=""  method="post">
                                    {% csrf_token %}
                                    <textarea placeholder="Your Comment" name="comment"></textarea>
                                    <button type="submit"><i class="fa fa-location-arrow"></i>Review</button>
                                </form>
                            </div>
                            {% endif %}
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="anime__details__sidebar">
                                <div class="section-title">
                                    <h5>you might like...</h5>
                                </div>
                                {% for like in you_might_like %}
                                <div class="product__sidebar__view__item set-bg" data-setbg="{{ like.image.url }}">
                                    
                                    <div class="view"><i class="fa fa-eye"></i> {{ like.views }}</div>
                                    <h5><a href="{% url 'movie_detail' like.slug %}">{{ like.title }}</a></h5>
                                </div>
                               {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Anime Section End -->
    
            <!-- Footer Section Begin -->
    {% endblock %}
        